In [1]:
import numpy as np
import damask
import shutil
import os
from math import * 
os.getcwd()
print("The current directory is: ")
print(os.getcwd())

The current directory is: 
c:\Users\springnuance\Desktop\DAMASK3-Processing-Project


### Converting Dream3D geom file to .vti file and save it

In [2]:
# Do not modify these variables below
dir = "convert_DAMASK2_to_DAMASK3"
material = "QP"
inputFile = f"{material}.geom"
outputFile = f"{material}.vti"
inputDir = f"{dir}/{inputFile}"
outputDir = f"{dir}/{outputFile}"


In [3]:
geometry = damask.Grid.load_ASCII(inputDir)

print(geometry)
print(geometry.material)

geometry.save(outputDir)

cells:  50 × 50 × 50
size:   15.0 × 15.0 × 15.0 m³
origin: 0.0   0.0   0.0 m
# materials: 125000
[[[     0   2500   5000 ... 117500 120000 122500]
  [    50   2550   5050 ... 117550 120050 122550]
  [   100   2600   5100 ... 117600 120100 122600]
  ...
  [  2350   4850   7350 ... 119850 122350 124850]
  [  2400   4900   7400 ... 119900 122400 124900]
  [  2450   4950   7450 ... 119950 122450 124950]]

 [[     1   2501   5001 ... 117501 120001 122501]
  [    51   2551   5051 ... 117551 120051 122551]
  [   101   2601   5101 ... 117601 120101 122601]
  ...
  [  2351   4851   7351 ... 119851 122351 124851]
  [  2401   4901   7401 ... 119901 122401 124901]
  [  2451   4951   7451 ... 119951 122451 124951]]

 [[     2   2502   5002 ... 117502 120002 122502]
  [    52   2552   5052 ... 117552 120052 122552]
  [   102   2602   5102 ... 117602 120102 122602]
  ...
  [  2352   4852   7352 ... 119852 122352 124852]
  [  2402   4902   7402 ... 119902 122402 124902]
  [  2452   4952   7452 ... 119

C:\Users\springnuance\AppData\Local\Temp\ipykernel_2432\710449337.py:1: DeprecationWarning: Support for ASCII-based geom format will be removed in DAMASK 3.0.0
  geometry = damask.Grid.load_ASCII(inputDir)
