In [9]:
import numpy as np
import damask
import shutil
import os
from math import * 
os.getcwd()
print("The current directory is: ")
print(os.getcwd())

The current directory is: 
c:\Users\springnuance\Desktop\DAMASK3-Processing-Project


### Converting Dream3D geom file to .vti file and save it

In [10]:
# Do not modify these variables below
dir = "convert_DAMASK2_to_DAMASK3"
material = "DP"
inputFile = f"{material}.geom"
outputFile = f"{material}.vti"
inputDir = f"{dir}/{inputFile}"
outputDir = f"{dir}/{outputFile}"


In [11]:
geometry = damask.Grid.load_ASCII(inputDir)

print(geometry)
print(geometry.material)

geometry.save(outputDir)

cells:  40 × 40 × 40
size:   0.0002 × 0.0002 × 0.0002 m³
origin: 0.0   0.0   0.0 m
# materials: 1091
[[[   0    1    4 ...  965 1016 1068]
  [   0    1    4 ...  965 1018 1068]
  [   0    1    4 ...  968 1018 1071]
  ...
  [   1    3    5 ... 1011 1068 1090]
  [   1    3    5 ... 1016 1068 1090]
  [   1    3    5 ... 1016 1068 1090]]

 [[   0    1    4 ...  965 1016 1068]
  [   0    1    4 ...  965 1018 1068]
  [   0    1    4 ...  968 1018 1071]
  ...
  [   1    3    5 ... 1011 1068 1090]
  [   1    3    5 ... 1016 1068 1090]
  [   1    4    5 ... 1016 1068 1090]]

 [[   0    1    4 ...  965 1016 1068]
  [   0    1    4 ...  965 1018 1068]
  [   0    1    4 ...  968 1018 1071]
  ...
  [   1    3    5 ... 1011 1068 1090]
  [   1    3    5 ... 1016 1068 1090]
  [   1    4    5 ... 1016 1068 1090]]

 ...

 [[   0    1    4 ...  965 1018 1068]
  [   0    1    4 ...  968 1018 1070]
  [   0    1    4 ...  970 1022 1071]
  ...
  [   1    3    5 ... 1016 1068 1090]
  [   1    3    5 ... 1016 

C:\Users\springnuance\AppData\Local\Temp\ipykernel_8480\710449337.py:1: DeprecationWarning: Support for ASCII-based geom format will be removed in DAMASK 3.0.0
  geometry = damask.Grid.load_ASCII(inputDir)
